package day8

import (
	"github.com/stretchr/testify/assert"
	"testing"
)

const example = `............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............`

func Test_part1(t *testing.T) {
	assert.Equal(t, 14, part1(example))
	assert.Equal(t, 320, part1(input))
}

func Test_part2(t *testing.T) {
	assert.Equal(t, 34, part2(example))
	assert.Equal(t, 1157, part2(input))
}
